// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBqrazS_DbVPHuEobS-cZzczlCK4aRD4I',
    appId: '1:387403274966:web:e799db3b910eda953c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    authDomain: 'smartedu-48462.firebaseapp.com',
    storageBucket: 'smartedu-48462.firebasestorage.app',
    measurementId: 'G-QC4C0SL4HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnXWs88nJmmRiSJZvUIM7KiFDyss8ea8',
    appId: '1:387403274966:android:81639752ff4d91d13c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    storageBucket: 'smartedu-48462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCGFqtsd1On929v9lVzJbgMSth3bITD8',
    appId: '1:387403274966:ios:f07e0049abf2705d3c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    storageBucket: 'smartedu-48462.firebasestorage.app',
    iosBundleId: 'com.ush.smartEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCGFqtsd1On929v9lVzJbgMSth3bITD8',
    appId: '1:387403274966:ios:f07e0049abf2705d3c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    storageBucket: 'smartedu-48462.firebasestorage.app',
    iosBundleId: 'com.ush.smartEdu',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBBqrazS_DbVPHuEobS-cZzczlCK4aRD4I',
    appId: '1:387403274966:web:e799db3b910eda953c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    authDomain: 'smartedu-48462.firebaseapp.com',
    storageBucket: 'smartedu-48462.firebasestorage.app',
    measurementId: 'G-QC4C0SL4HZ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBqrazS_DbVPHuEobS-cZzczlCK4aRD4I',
    appId: '1:387403274966:web:68e6ae8fc7d8edbc3c0777',
    messagingSenderId: '387403274966',
    projectId: 'smartedu-48462',
    authDomain: 'smartedu-48462.firebaseapp.com',
    storageBucket: 'smartedu-48462.firebasestorage.app',
    measurementId: 'G-7XVF83LNRS',
  );
}
